### PR TITLE
#790 FIX Comment minimization fails in certain self-hosted GHE

### LINKED ISSUE #790: Comment minimization fails in certain self-hosted GHE scenarious
### Describe the bug

_No response_

### Steps to reproduce

_No response_

### Expected behavior

1. The GraphQL endpoint is properly called and the comment is minimized

### Actual behavior

1. We are getting a 404

### Terrateam version & environment details

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by schonfinkel**
## Description

- Closes #790 

## Type of change

- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Documentation update
- [X] Other (explain):

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/terrateamio/terrateam/blob/main/CONTRIBUTING.md)
- [x] The pull request title follows this format:
      `ISSUE_NUMBER ACTION_TYPE Short description` (e.g., `123 ADD Feature description`)
- [x] I have added tests and documentation (if applicable)
- [x] My changes generate no new warnings/errors and do not break existing functionality

### CODE REVIEW

File: code/src/terrat_github/terrat_github.ml [hunk 1]
```diff
@@ -463,37 +490,19 @@ let minimize_comment ~owner ~repo ~comment_id client =
...
-      | `OK -> Abb.Future.return (Ok ()))
+      | `OK -> Abb.Future.return (Ok ())
+      | `Not_found -> (
+          let url = "/api/graphql" in
+          let request = create_minimize_request url node_id in
+          call client request
+          >>= fun resp ->
+          match Openapi.Response.value resp with
+          | `OK -> Abb.Future.return (Ok ())
+          | `Not_found -> Abb.Future.return (Ok ())))
```
Comment (orbitz) [inline code/src/terrat_github/terrat_github.ml]: This can actually fail because we ignore all failures in the `terrat_vcs_api_github` module.  (and `not_found` causes a failure on the line below so that should probably be made consistent.

**Review by orbitz — APPROVED** [review]

**Review by orbitz — APPROVED** [review]

**Review by joshpollara — APPROVED** [review]
