### PR TITLE
#813 FIX Forcefully compact all elements, including hooks

### LINKED ISSUE #813: Reproduce and GitHub API bug when posting "large" comments
### Describe the bug

We are getting some logs informing that certain comments are too large, even though we already compact such comments.

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Actual behavior

```
[2025-09-03T12:39:53] [INFO] [vcs_api_github] <GUID> : COMMENT_ON_PULL_REQUEST : `Unprocessable_entity (
                                              { Additional_properties.Make.primary =
                                                { Primary.documentation_url =
                                                  "https://docs.github.com/rest/issues/comments#create-an-issue-comment";
                                                  errors =
                                                  (Some [{ Additional_properties.Make.primary =
                                                           { Primary.Errors.Items.Primary.code =
                                                             "unprocessable";
                                                             field =
                                                             (Some "data");
                                                             index = None;
                                                             message =
                                                             (Some "Body is too long (maximum is 65536 characters)");
                                                             resource =
                                                             (Some "IssueComment");
                                                             value = None };
                                                           additional = [] }
                                                          ]);
                                                  message =
                                                  "Validation Failed" };
                                                additional =
                                                [("status", `String ("422"))]
                                                })
```

### Terrateam version & environment details

_No response_

### Additional context

1. Add a log to `terrat_vcs_github_comment` on `post_comment` which shows whether or not the comment is compacted, also with its `rendered_length`, and the number of dirspaces.
2. On `rendered_length`, use the length of the encoded json. Also have a log comparing the lenght of the compacted json and the original json.
3. If we get a failure on `post_comment` and its not compacted, set it to compacted and run it again. If the comment posting still fails, log an error and do a comment without the dirspaces.

### PR DESCRIPTION
**Pull request by schonfinkel**
## Description

- Closes #813 

## Type of change

- [X] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Documentation update
- [ ] Other (explain):

## Checklist

- [ ] I have read the [contributing guidelines](https://github.com/terrateamio/terrateam/blob/main/CONTRIBUTING.md)
- [ ] The pull request title follows this format:
      `ISSUE_NUMBER ACTION_TYPE Short description` (e.g., `123 ADD Feature description`)
- [ ] I have added tests and documentation (if applicable)
- [ ] My changes generate no new warnings/errors and do not break existing functionality

### CODE REVIEW

File: code/src/terrat_vcs_github_comment/terrat_vcs_github_comment.ml [hunk 1]
```diff
@@ -238,7 +238,8 @@ module S = struct
     Api.minimize_pull_request_comment ~request_id t.client t.pull_request comment_id
 
   let post_comment t els =
-    let open Abbs_future_combinators.Infix_result_monad in
+    (* let open Abbs_future_combinators.Infix_result_monad in *)
```
Comment (orbitz) [inline code/src/terrat_vcs_github_comment/terrat_vcs_github_comment.ml]: Delete the comment

**Review by orbitz — APPROVED** [review]
